language: node_js
node_js:
  - lts/*
  - lts/dubnium
  - lts/carbon
  - lts/boron
  - lts/argon 
  - stable
  - node
before_script:
  - npm install -g retire
script:
  - npm audit
  - retire
  - npm test 
